In [42]:
import pylab as pl
import pprint
import os
import json
import sys
import pandas as pd
import pprint
import re
try:
    import urllib2 as urllib
except ImportError:
    import urllib.request as urllib

apiKey='81e3ec91-9d70-49cf-8a2a-d5a0adec6c21'#sys.argv[1]
busLine='B52'#sys.argv[2]
url='http://bustime.mta.info/api/siri/vehicle-monitoring.json?key=%s&VehicleMonitoringDetailLevel=calls&LineRef=%s' % (apiKey, busLine)


response = urllib.urlopen(url)
data = response.read().decode("utf-8")
data = json.loads(data)
allBus=data['Siri']['ServiceDelivery']['VehicleMonitoringDelivery'][0]['VehicleActivity']

df=pd.DataFrame(columns=['Latitude', 'Longitude', 'Stop Name', 'Stop Status'])
k=0
find=['approaching', '1 stop away']
print (len(allBus))
for i in allBus:
    i=i['MonitoredVehicleJourney']
    vehicleLocation=i['VehicleLocation']
    onwardCalls=i['OnwardCalls']
    if len(onwardCalls)<1:
        row=[vehicleLocation['Latitude'], vehicleLocation['Longitude'], 'N/A', 'N/A']
    else:
        onwardCall=onwardCalls['OnwardCall']
        for j in onwardCall:
            presDist=j['Extensions']['Distances']['PresentableDistance']
            stopName=j['StopPointName']
            if(presDist in find):
                row=[vehicleLocation['Latitude'], vehicleLocation['Longitude'], stopName, presDist]
                break
            else:
                row=[vehicleLocation['Latitude'], vehicleLocation['Longitude'], 'N/A', 'N/A']
        df.loc[k]=row
    k+=1
#     break
df.to_csv()

11
0 found~
1 found~
3 found~
4 found~
6 found~
7 found~
8 found~
9 found~
10 found~

     Latitude  Longitude                   Stop Name  Stop Status
0   40.686177 -73.970115     GREENE AV/VANDERBILT AV  1 stop away
1   40.687041 -73.962795     GREENE AV/WASHINGTON AV  1 stop away
3   40.695189 -73.916497          GATES AV/WILSON AV  approaching
4   40.688248 -73.932742      GATES AV/STUYVESANT AV  approaching
6   40.693263 -73.989108  ADAMS ST/BKLYN SUPREME CRT  approaching
7   40.687322 -73.960331        GREENE AV/CLASSON AV  approaching
8   40.688809 -73.927924         GATES AV/PATCHEN AV  approaching
9   40.700999 -73.910722         GATES AV/WYCKOFF AV  approaching
10  40.685214 -73.959258          GREENE AV/GRAND AV  1 stop away